import React from 'react';
import { Card, List, Typography, Space } from 'antd';
import { RiseOutlined } from '@ant-design/icons';

const { Title, Text } = Typography;

interface DeliveryPartner {
  id: number; // Use string if your delivery partner IDs are strings (like ObjectId)
  name: string;
  earnings: number; // Represents total earnings generated by the delivery partner
}

interface TopDeliveryPartnersCardProps {
  title?: string;
  growthPercentage: number; // Represents growth in earnings, deliveries, etc.
  partners: DeliveryPartner[]; // Use partners instead of shops
}

const TopDeliveryPartnersCard: React.FC<TopDeliveryPartnersCardProps> = ({
  title = 'Top Delivery Partners',
  growthPercentage,
  partners,
}) => {
  return (
    <Card
      style={{
        width: 400,
        background: 'linear-gradient(145deg, #0d0d32, #14145a)',
        borderRadius: '12px',
        boxShadow: '2px 2px 8px rgba(0, 0, 0, 0.3)',
        color: 'white',
      }}
    >
      <Space direction="vertical" size="middle" style={{ width: '100%' }}>
        <Title level={5} style={{ color: 'white', margin: 0 }}>
          {title}
        </Title>
        <Text style={{ color: 'lightgreen' }}>
          <RiseOutlined /> +{growthPercentage}% this month
        </Text>

        <List
          itemLayout="horizontal"
          dataSource={partners}
          renderItem={(partner) => (
            <List.Item style={{ borderBottom: 'none', padding: '8px 0' }}>
              <List.Item.Meta
                title={<Text style={{ color: 'white' }}>{partner.name}</Text>}
                description={
                  <span>
                    <Text style={{ color: 'rgba(255, 255, 255, 0.6)' }}>
                      Earnings: ₹{partner.totalEarnings?.toFixed(2)} {/* Format earnings nicely */}
                    </Text>
                  </span>
                }
              />
            </List.Item>
          )}
        />
      </Space>
    </Card>
  );
};

export default TopDeliveryPartnersCard;
