import React from 'react';
import { Card, List, Typography, Space } from 'antd';
// import { RiseOutlined } from '@ant-design/icons';

const { Title, Text } = Typography;

interface Shop {
  id: number; // Use string if your shop IDs are strings (like ObjectId)
  name: string;
  icon: React.ReactNode; // You might want to use an actual icon or image here
  sales: number; // Represents sales or revenue generated by the shop
}

interface TopShopsCardProps {
  title?: string;
  growthPercentage: number; // Represents growth in sales, visits, etc.
  stores: Shop[]; // Use shops instead of products
}

const TopStoresCard: React.FC<TopShopsCardProps> = ({
  title = 'Top Shops',
  // growthPercentage,
  stores,
}) => {
  return (
    <Card
      style={{
        width: 400,
        background: 'linear-gradient(145deg, #0d0d32, #14145a)',
        borderRadius: '12px',
        boxShadow: '2px 2px 8px rgba(0, 0, 0, 0.3)',
        color: 'white',
      }}
      // Note: styles prop is deprecated, use style prop directly
    >
      <Space direction="vertical" size="middle" style={{ width: '100%' }}>
        <Title level={5} style={{ color: 'white', margin: 0 }}>
          {title}
        </Title>
        {/*  <Text style={{ color: 'lightgreen' }}>
          <RiseOutlined /> +{growthPercentage}% this month
        </Text> */}

        <List
          itemLayout="horizontal"
          dataSource={stores}
          renderItem={(shop) => (
            <List.Item style={{ borderBottom: 'none', padding: '8px 0' }}>
              <List.Item.Meta
                // Optional: if you have a shop logo or image
                // avatar={shop.icon}
                title={<Text style={{ color: 'white' }}>{shop.name}</Text>}
                description={
                  <span>
                    <Text style={{ color: 'rgba(255, 255, 255, 0.6)' }}>
                      Sales: ₹{shop.totalSales} {/* Format sales nicely */}
                    </Text>
                  </span>
                }
              />
            </List.Item>
          )}
        />
      </Space>
    </Card>
  );
};

export default TopStoresCard;
